services:
  - type: web
    name: jstcuriousai42-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: HF_API_TOKEN
        value: your_actual_huggingface_token
